CLI interfaces for new work modes: convert P2X configs to JSON

diff --git a/src-js/p2xjs b/src-js/p2xjs
--- a/src-js/p2xjs
+++ b/src-js/p2xjs
@@ -6,14 +6,38 @@ if ! test -x $(which $NODE); then
    NODE=node
 fi
 
+mode=p2x-main
+
+case $1 in
+    (scanconf-xml2json)
+        mode=$1
+        shift
+    ;;
+    (parseconf-text2json)
+        mode=$1
+        shift
+    ;;
+    # (parse-text2xml)
+    #     mode=$1
+    #     shift
+    # ;;
+    # (parse-xml2json)
+    #     mode=$1
+    #     shift
+    # ;;
+esac
+
 srcdir=$(dirname $BASH_SOURCE)
 
-main_src=p2x-main.js
+main_src=$mode.js
 
 if test -r $srcdir/$main_src; then
     file=$srcdir/$main_src
 elif test -r $srcdir/../share/p2x/js/$main_src; then
-    file=$srcdir/../share/p2x/js/p2x-main.js
+    file=$srcdir/../share/p2x/js/$main_src
+else
+    echo "error: JS main program $main_src not found"
+    exit 1
 fi
 
 $NODE $file $*
